Update version to 1.1.9 SNAPSHOT
TAMULib/mod-workflow pull request #129
Opened 2024-04-02 15:59 UTC by jmicah

2024-04-03 18:14 UTC, wwelling approved these changes

2024-04-04 15:34 UTC, kaladay requested changes
There are two additional pom files that need changing.
- https://github.com/TAMULib/mod-workflow/blob/7e0462eede18b0b9f2fdf14ddbc82f07cfed5061/components/pom.xml
- https://github.com/TAMULib/mod-workflow/blob/7e0462eede18b0b9f2fdf14ddbc82f07cfed5061/service/pom.xml

2024-04-09 15:39 UTC, Dbreck-TAMU approved these changes

2024-04-11 13:15 UTC, wwelling commented
Thanks @kaladay. They have been updated accordingly.

2024-04-11 13:15 UTC, wwelling approved these changes

2024-04-26 20:53 UTC, kaladay approved these changes

2024-05-09 21:03 UTC, merged